OrdererOrgs:
  - Name: Orderer
    Domain: evote.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
      - Hostname: orderer2
      - Hostname: orderer3
      - Hostname: orderer4
      - Hostname: orderer5

PeerOrgs:
  - Name: OrgIT
    Domain: itcae.evote.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: OrgCE
    Domain: ce.evote.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: OrgKOR
    Domain: kor.evote.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: OrgENG
    Domain: eng.evote.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
